export type NUMERICODE_INPUT = "NUMERICODE_INPUT";
export const NUMERICODE_INPUT: NUMERICODE_INPUT = "NUMERICODE_INPUT";
export type DECODED_NUMERICODE = "DECODED_NUMERICODE";
export const DECODED_NUMERICODE: DECODED_NUMERICODE = "DECODED_NUMERICODE";
export type DECODING_ERROR = "DECODING_ERROR";
export const DECODING_ERROR: DECODING_ERROR = "DECODING_ERROR";